var keyMirror = require('react/lib/keyMirror');

module.exports = {

  ActionTypes: keyMirror({
    EMPLOYEE_REQUEST_WEEK: null,
    EMPLOYEE_REQUEST_WEEK_ERROR: null,
    EMPLOYEE_REQUEST_WEEK_SUCCESS: null,

    EMPLOYEE_LIST_REQUEST: null,
    EMPLOYEE_LIST_SEARCH: null,
    EMPLOYEE_LIST_LETTER: null,
    EMPLOYEE_LIST_REQUEST_ERROR: null,
    EMPLOYEE_LIST_REQUEST_SUCCESS: null,
    EMPLOYEE_UPLOAD_IMAGE: null,

    PATIENT_REQUEST_DAY: null,
    PATIENT_REQUEST_DAY_ERROR: null,
    PATIENT_REQUEST_DAY_SUCCESS: null,

    PATIENT_REQUEST_WEEK: null,
    PATIENT_REQUEST_WEEK_ERROR: null,
    PATIENT_REQUEST_WEEK_SUCCESS: null,

    DASHBOARD_REQUEST_VIEWS: null,
    DASHBOARD_REQUEST_VIEWS_ERROR: null,
    DASHBOARD_REQUEST_VIEWS_SUCCESS: null,
    DASHBOARD_REQUEST_VIEWS_DELETED: null,

    DASHBOARD_REQUEST_LOGIN: null,
    DASHBOARD_REQUEST_LOGIN_ERROR: null,
    DASHBOARD_REQUEST_LOGIN_SUCCESS: null,

    DASHBOARD_REQUEST_LOGGEDIN_SUCCESS: null,
    DASHBOARD_REQUEST_LOGOUT_SUCCESS: null,
    DASHBOARD_REQUEST_ERROR_401: null,

    DASHBOARD_REQUEST_FORM_SUCCESS: null,
    DASHBOARD_REQUEST_USERS_SUCCESS: null,
    DASHBOARD_REQUEST_USER_SUCCESS: null,
    DASHBOARD_REQUEST_UNITS_SUCCESS: null,
    DASHBOARD_REQUEST_PERSONS_SUCCESS: null,
    DASHBOARD_REQUEST_TYPES_SUCCESS: null,
    DASHBOARD_REQUEST_VIEW_SUCCESS: null,
    EMPLOYEE_UPLOAD_PROGRESS: null,
    EMPLOYEE_REMOVE_IMAGE: null

  }),

  PayloadSources: keyMirror({
    SERVER_ACTION: null,
    VIEW_ACTION: null
  })

};
